import './global.css';
import {Sidebar} from "../components/Sidebar";
import Provider from "./providers";
import Providers from "./providers";

export const metadata = {
  title: 'Welcome to kabisa-fe-quotes',
  description: 'Generated by create-nx-workspace',
};


export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={"min-h-screen text-gray-100 bg-slate-900"}>
    <body className={"min-h-screen bg-violet-900/25"}>
    <Providers>

      <Sidebar>

        <main className="py-10 lg:pl-72">
          <div className="px-4 sm:px-6 lg:px-8">{children}</div>
        </main>
      </Sidebar>
    </Providers>
    </body>
    </html>
  );
}
