import './global.css';
import {Sidebar} from "../components/Sidebar";
import Providers from "./providers";

export const metadata = {
  title: 'Welcome to kabisa-fe-quotes',
  description: 'Generated by create-nx-workspace',
};


export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={"h-full w-full text-gray-100 bg-violet-950"}>
    <body className={"h-full w-full"}>

    <Providers>

      <Sidebar/>


      <div className="py-10 lg:pl-72 h-full w-full">
        <div className=" px-4 sm:px-6 lg:px-8 h-full">{children}</div>
      </div>
    </Providers>
    </body>
    </html>
  );
}
